export const fonts = {
  PoppinsBlack: "PoppinsBlack",
  PoppinsExtraBoldItalic: "PoppinsExtraBoldItalic",
  PoppinsExtraLight: "PoppinsExtraLight",
  PoppinsMedium: "PoppinsMedium",
  PoppinsMediumItalic: "PoppinsMediumItalic",
  PoppinsThinItalic: "PoppinsThinItalic",
  PoppinsBlackItalic: "PoppinsBlackItalic",
  PoppinsBold: "PoppinsBold",
  PoppinsBoldItalic: "PoppinsBoldItalic",
  PoppinsExtraBold: "PoppinsExtraBold",
  PoppinsExtraLightItalic: "PoppinsExtraLightItalic",
  PoppinsItalic: "PoppinsItalic",
  PoppinsLight: "PoppinsLight",
  PoppinsLightItalic: "PoppinsLightItalic",
  PoppinsRegular: "PoppinsRegular",
  PoppinsSemiBold: "PoppinsSemiBold",
  PoppinsSemiBoldItalic: "PoppinsSemiBoldItalic",
  PoppinsThin: "PoppinsThin",
};
